name:                inline-asm
version:             0.1.0.0
github:              "0xd34df00d/inline-asm"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2020 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Inline some Assembly in ur Haskell!
category:            FFI

description:         Please see the README on GitHub at <https://github.com/0xd34df00d/inline-asm#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-prim
- template-haskell >= 2.15.0.0
- uniplate

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  inline-asm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inline-asm

tests:
  inline-asm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inline-asm
    - hspec
    - QuickCheck
