name:                inline-asm
version:             0.4.0.2
github:              "0xd34df00d/inline-asm"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2020 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Inline some Assembly in ur Haskell!
category:            FFI

description:         Please see the README on GitHub at <https://github.com/0xd34df00d/inline-asm#readme>

flags:
  with-examples:
    description: Build examples
    manual: false
    default: false

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- either
- ghc-prim
- megaparsec
- mtl
- parser-combinators
- primitive
- template-haskell >= 2.16.0.0
- uniplate

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  ex-rdtsc:
    main:                Rdtsc.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - inline-asm
    - interpolate
    - lens
    - Chart
    - Chart-cairo
    when:
    - condition: flag(with-examples)
      then:
        buildable: true
      else:
        buildable: false

tests:
  inline-asm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inline-asm
    - hspec
    - hspec-core
    - QuickCheck
